apiVersion: v1
kind: Service
metadata:
  labels:
    service: unomi
  name: unomi
  namespace: unomi
spec:
  type: ClusterIP
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8181
    - name: "9443"
      port: 9443
      targetPort: 9443
    - name: "8102"
      port: 8102
      targetPort: 8102
  selector:
    service: unomi