apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unomi-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sekharrfk/rfk-data-unomi-config
    targetRevision: staging-deployment
    path: infra/k8s/kustomize/overlays/staging/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: unomi
  syncPolicy:
    automated:
      selfHeal: true
      prune: true