apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unomi-34957223
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sekharrfk/rfk-data-unomi-config
    targetRevision: main
    path: infra/k8s/kustomize/overlays/prod-us/34957223
  destination:
    server: https://kubernetes.default.svc
    namespace: unomi
  syncPolicy:
    automated:
      selfHeal: true
      prune: true